import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full py-4 bg-gray-100 dark:bg-gray-900 text-center font-bold">
      {/* Next JS Beginning */}
      <Navigation/>
    </header>
        {children}
        <footer className="w-full py-4 bg-gray-100 dark:bg-gray-900 text-center">
      &copy; 2025 My Next JS App
    </footer>
      </body>
    </html>
  );
}
